[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = true

[programs.localnet]
dutch-auction = "25MgjiKAVySForPXcZdizT4jPa1jcSPGhdfJUfLStGsz"
faucet = "4h1ELKdFXCYHAB3pvEQgyxExNqVUWz5ZZVjKP516VBjA"
solana = "Crgf2RxE1xdvcz9iqK3QFWrZnguPmtFuNU9wpJRLvi4d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 programs/**/*.ts"
# test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 programs/dutch*/*.ts"
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 programs/faucet/*.ts"
